const BASE = 'https://www.ridego.com.ua';
const PROJECT = 'ridego-6f981';
const BOTS = /googlebot|bingbot|slurp|duckduckbot|baiduspider|yandexbot|facebookexternalhit|twitterbot|linkedinbot|telegrambot|whatsapp|applebot|mj12bot|ahrefsbot|semrushbot|petalbot|bytespider|google-inspectiontool|google-structured-data-testing|storebot|developers\.google/i;
const CATEGORIES = {
  'elektrosamokaty':   { name: 'Електросамокати', icon: '⚡', desc: 'Купити електросамокат в Україні — великий вибір нових та вживаних електросамокатів від приватних продавців і магазинів за вигідними цінами.' },
  'velosypedy':        { name: 'Велосипеди', icon: '🚲', desc: 'Купити велосипед в Україні — гірські, міські, дорожні велосипеди від приватних продавців за доступними цінами.' },
  'elektrovelosypedy': { name: 'Електровелосипеди', icon: '🚴', desc: 'Купити електровелосипед в Україні — новітні моделі електровелосипедів для міста та бездоріжжя.' },
  'elektroskutery':    { name: 'Електроскутери', icon: '🛵', desc: 'Купити електроскутер в Україні — широкий вибір електроскутерів для міських поїздок за найкращими цінами.' },
  'elektromotocykly':  { name: 'Електромотоцикли', icon: '🏍', desc: 'Купити електромотоцикл в Україні — потужні електромотоцикли для активного відпочинку та щоденних поїздок.' },
};
const BRANDS = {
  'kukirin': {
    name: 'KuKirin', firebaseNames: ['Kukirin','KuKirin','Kugoo'], category: 'Електросамокати', catSlug: 'elektrosamokaty', icon: '⚡',
    title: 'Купити електросамокат KuKirin (Кукірін) в Україні — ціни, моделі | RideGO',
    h1: 'Електросамокати KuKirin — купити в Україні',
    metaDesc: 'Електросамокати KuKirin (Кукірін, Kugoo Kirin) — купити в Україні на маркетплейсі RideGO. Моделі G2, G2 Pro, G2 Max, G3, G4, M4 Pro, S1 Max. Нові та б/в, ціни від продавців по всій Україні.',
    keywords: 'купити KuKirin, KuKirin ціна, електросамокат KuKirin, купити Kukirin, купити Kugoo Kirin, купити Кукірін, купити Кукирін, купити Кукирин, KuKirin Україна, KuKirin Київ, KuKirin б/в',
    introHtml: '<div style="background:#f0fdf4;border-radius:16px;padding:24px 28px;margin-bottom:28px;line-height:1.8;font-size:15px;color:#333"><h2 style="font-size:20px;font-weight:800;margin-bottom:12px;color:#111">KuKirin (Кукірін) — електросамокати для міста та бездоріжжя</h2><p><strong>KuKirin</strong> (також відомий як <strong>Kugoo Kirin</strong>, Кукірін, Кукирін) — один із найпопулярніших брендів електросамокатів в Україні. Бренд пропонує широку лінійку моделей: від компактних міських (<strong>KuKirin S1 Max</strong>, <strong>KuKirin A1</strong>) до потужних позашляховиків (<strong>KuKirin G2 Pro</strong>, <strong>KuKirin G3</strong>, <strong>KuKirin G4</strong>) та моделей із сидінням (<strong>KuKirin M4 Pro</strong>, <strong>KuKirin M5 Pro</strong>).</p><p style="margin-top:12px">На маркетплейсі <strong>RideGO</strong> ви можете <strong>купити електросамокат KuKirin</strong> як новий, так і б/в — від приватних продавців та магазинів по всій Україні. Порівнюйте ціни, характеристики та стан, обирайте найкращу пропозицію та зв\'яжіться з продавцем напряму.</p><h3 style="font-size:17px;font-weight:700;margin-top:20px;margin-bottom:10px;color:#111">Популярні моделі KuKirin</h3><ul style="margin:0;padding-left:20px;color:#444"><li><strong>KuKirin G2</strong> — 800 Вт, 48V 15Ah, до 60 км запас ходу. Універсальна міська модель.</li><li><strong>KuKirin G2 Pro</strong> — покращена версія G2 з посиленою рамою та більшими гальмами.</li><li><strong>KuKirin G2 Max</strong> — 1000 Вт, 20Ah батарея, до 70 км ходу. Для далеких поїздок.</li><li><strong>KuKirin G3 / G3 Pro</strong> — подвійний двигун до 1200 Вт, пневматичні шини, потужна амортизація.</li><li><strong>KuKirin G4</strong> — 2000 Вт, до 69 км/год. Флагман для досвідчених райдерів.</li><li><strong>KuKirin M4 Pro</strong> — з сидінням, 1500 Вт, NFC-ключ. Комфорт для тривалих поїздок.</li><li><strong>KuKirin S1 Max</strong> — легкий (16 кг), 350 Вт, складний. Ідеальний для останньої милі.</li><li><strong>KuKirin T3</strong> — 800 Вт, 15.6Ah, 10-дюймові колеса. Золота середина ціна/якість.</li><li><strong>KuKirin C1 Pro</strong> — 14-дюймові колеса, 26Ah, до 100 км ходу. Для комфортних далеких поїздок.</li></ul><h3 style="font-size:17px;font-weight:700;margin-top:20px;margin-bottom:10px;color:#111">Чому купити KuKirin на RideGO?</h3><p>На RideGO зібрані оголошення від продавців по всій Україні — Київ, Харків, Одеса, Дніпро, Львів та інші міста. Ви бачите реальні фото, точні характеристики та ціни без прихованих комісій. Купити електросамокат Кукірін на RideGO — це зручно, безпечно та вигідно.</p></div>',
    faqItems: [
      { q: 'Скільки коштує електросамокат KuKirin в Україні?', a: 'Ціни на електросамокати KuKirin в Україні починаються від ~14 000 грн за легкі моделі (S1 Max) і до ~40 000 грн за флагмани (G4, G2 Master). Вживані моделі можна знайти значно дешевше.' },
      { q: 'Який KuKirin вибрати для міста?', a: 'Для щоденних міських поїздок підійдуть KuKirin G2 (800 Вт, до 60 км ходу) або KuKirin S1 Max (легкий, 16 кг). Для поганих доріг — KuKirin G2 Pro з покращеною амортизацією.' },
      { q: 'Чим KuKirin відрізняється від Kugoo?', a: 'KuKirin — це ребрендинг Kugoo Kirin. Фактично це той самий виробник, але під новим брендом KuKirin. Моделі серії Kirin (G2, G3, M4 Pro) тепер випускаються під назвою KuKirin.' },
      { q: 'Де купити оригінальний KuKirin в Україні?', a: 'На маркетплейсі RideGO зібрані оголошення від продавців по всій Україні. Ви можете порівняти ціни, перевірити рейтинг продавця та обрати найкращу пропозицію.' },
      { q: 'Який запас ходу у електросамокатів KuKirin?', a: 'Залежно від моделі: KuKirin S1 Max — до 40 км, G2 — до 60 км, G2 Max — до 70 км, C1 Pro — до 100 км. Реальний пробіг залежить від ваги райдера, рельєфу та швидкості.' }
    ],
    relatedSearches: ['купити kukirin g2','kukirin g2 pro ціна','kukirin g4 купити','kukirin m4 pro ціна','електросамокат kukirin ціна','kukirin або ninebot','kukirin запчастини']
  },
};
function escHtml(str) { return String(str||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
async function getListingsByCategory(catName) {
  try {
    const url = `https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents:runQuery`;
    const body = { structuredQuery: { from:[{collectionId:'listings'}], where:{compositeFilter:{op:'AND',filters:[{fieldFilter:{field:{fieldPath:'cat'},op:'EQUAL',value:{stringValue:catName}}},{fieldFilter:{field:{fieldPath:'status'},op:'EQUAL',value:{stringValue:'active'}}}]}}, orderBy:[{field:{fieldPath:'createdAt'},direction:'DESCENDING'}], limit:20 } };
    const res = await fetch(url, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) });
    if (!res.ok) return [];
    const data = await res.json();
    return data.filter(d=>d.document).map(d=>{ const f=d.document.fields||{}; const id=d.document.name.split('/').pop(); return { id, title:f.title?.stringValue||'', price:f.price?.integerValue||f.price?.doubleValue||'', city:f.city?.stringValue||'', condition:f.condition?.stringValue||'', img:f.img?.stringValue||'' }; });
  } catch(e) { return []; }
}
async function getListingsByBrand(brandNames, limit) {
  const all=[]; const seen=new Set();
  for (const bn of brandNames) {
    try {
      const url = `https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents:runQuery`;
      const body = { structuredQuery: { from:[{collectionId:'listings'}], where:{compositeFilter:{op:'AND',filters:[{fieldFilter:{field:{fieldPath:'status'},op:'EQUAL',value:{stringValue:'active'}}},{fieldFilter:{field:{fieldPath:'brand'},op:'EQUAL',value:{stringValue:bn}}}]}}, limit:limit||30 } };
      const res = await fetch(url, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) });
      if (res.ok) { const data=await res.json(); data.filter(d=>d.document).forEach(d=>{ const id=d.document.name.split('/').pop(); if(!seen.has(id)){seen.add(id); const f=d.document.fields||{}; all.push({id,title:f.title?.stringValue||'',price:f.price?.integerValue||f.price?.doubleValue||'',city:f.city?.stringValue||'',condition:f.condition?.stringValue||'',img:f.img?.stringValue||''});} }); }
    } catch(e) {}
  }
  return all.slice(0,limit||30);
}
function getParam(req,key) { if(req.query&&req.query[key]) return req.query[key]; try{ const qs=(req.url||'').split('?')[1]||''; for(const p of qs.split('&')){const[k,v]=p.split('='); if(decodeURIComponent(k||'')===key) return decodeURIComponent(v||'');} }catch(e){} return ''; }
function card(l) { const price=l.price?Number(l.price).toLocaleString('uk')+' грн':''; return `<article style="border:1px solid #eee;border-radius:12px;overflow:hidden">${l.img?`<a href="${BASE}/listing/${l.id}"><img src="${escHtml(l.img)}" alt="${escHtml(l.title+(l.city?' купити в '+l.city:''))}" width="400" height="240" loading="lazy" style="width:100%;height:160px;object-fit:cover;display:block"></a>`:''}<div style="padding:12px"><a href="${BASE}/listing/${l.id}" style="font-weight:700;color:#111;text-decoration:none;font-size:15px;display:block;margin-bottom:4px">${escHtml(l.title)}</a>${price?`<div style="color:#1db954;font-weight:800;font-size:16px;margin-bottom:4px">${price}</div>`:''}<div style="color:#888;font-size:13px">${escHtml(l.city)}${l.condition?' · '+escHtml(l.condition):''}</div></div></article>`; }
function shell(head,body) { return `<!DOCTYPE html><html lang="uk"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">${head}<link rel="icon" type="image/svg+xml" href="/favicon.svg"><style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',Arial,sans-serif;max-width:980px;margin:0 auto;padding:20px;color:#222;background:#fff}header{padding:16px 0;border-bottom:2px solid #1db954;margin-bottom:20px}header a{font-size:26px;font-weight:800;color:#111;text-decoration:none}header a span{color:#1db954}.bc{font-size:13px;color:#888;margin-bottom:20px}.bc a{color:#1db954;text-decoration:none}.bc span{margin:0 5px;color:#ccc}h1{font-size:clamp(22px,4vw,34px);font-weight:800;margin-bottom:8px;color:#111}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:16px;margin-bottom:32px}footer{padding:20px 0;border-top:1px solid #eee;font-size:13px;color:#999;text-align:center;margin-top:32px}footer a{color:#1db954;text-decoration:none;margin:0 8px}details summary{list-style:none}details summary::-webkit-details-marker{display:none}details summary::before{content:'▸ ';color:#1db954}details[open] summary::before{content:'▾ '}</style></head><body><header><a href="${BASE}">Ride<span>GO</span></a></header>${body}<footer><span>© 2024–2026 RideGO</span><a href="${BASE}">Головна</a><a href="${BASE}/catalog">Каталог</a><a href="${BASE}/news">Новини</a><a href="${BASE}/faq">FAQ</a></footer></body></html>`; }

module.exports = async (req, res) => {
  const ua=req.headers['user-agent']||''; const isBot=BOTS.test(ua);
  const slug=getParam(req,'slug').replace(/[^a-zA-Z0-9_-]/g,'');
  const brandSlug=getParam(req,'brand').replace(/[^a-zA-Z0-9_-]/g,'').toLowerCase();
  const isBrand=!!brandSlug; const brand=isBrand?BRANDS[brandSlug]:null; const catInfo=!isBrand?CATEGORIES[slug]:null;
  if(isBrand&&!brand){res.setHeader('Location',`${BASE}/catalog`);return res.status(302).end();}
  if(!isBot){const fs=require('fs');const path=require('path');try{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, must-revalidate');return res.status(200).send(html);}catch(e){res.setHeader('Location',isBrand?`${BASE}/brand/${brandSlug}`:`${BASE}/category/${slug}`);return res.status(302).end();}}

  if(isBrand&&brand){
    const listings=await getListingsByBrand(brand.firebaseNames,30);
    const lHtml=listings.length?listings.map(l=>card(l)).join('\n'):`<p style="color:#888;grid-column:1/-1">Оголошень поки немає — <a href="${BASE}/add" style="color:#1db954">додайте першим!</a></p>`;
    const ils=JSON.stringify({"@context":"https://schema.org","@type":"ItemList","name":`${brand.name} — купити в Україні | RideGO`,"url":`${BASE}/brand/${brandSlug}`,"numberOfItems":listings.length,"itemListElement":listings.slice(0,20).map((l,i)=>({"@type":"ListItem","position":i+1,"url":`${BASE}/listing/${l.id}`,"name":l.title}))});
    const bcs=JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"RideGO","item":BASE},{"@type":"ListItem","position":2,"name":"Каталог","item":`${BASE}/catalog`},{"@type":"ListItem","position":3,"name":brand.category,"item":`${BASE}/category/${brand.catSlug}`},{"@type":"ListItem","position":4,"name":brand.name,"item":`${BASE}/brand/${brandSlug}`}]});
    const faqs=brand.faqItems?JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":brand.faqItems.map(f=>({"@type":"Question","name":f.q,"acceptedAnswer":{"@type":"Answer","text":f.a}}))}):''
    const faqH=brand.faqItems?`<section style="margin-bottom:32px"><h2 style="font-size:19px;font-weight:800;margin-bottom:16px;color:#111">Часті питання про ${escHtml(brand.name)}</h2>${brand.faqItems.map(f=>`<details style="margin-bottom:10px;border:1px solid #eee;border-radius:10px;overflow:hidden"><summary style="padding:14px 18px;font-weight:700;font-size:15px;cursor:pointer;background:#fafafa;color:#111">${escHtml(f.q)}</summary><div style="padding:14px 18px;font-size:14px;color:#555;line-height:1.7">${escHtml(f.a)}</div></details>`).join('')}</section>`:'';
    const relH=brand.relatedSearches?`<section style="margin-bottom:32px"><h2 style="font-size:16px;font-weight:700;margin-bottom:12px;color:#111">Популярні запити</h2><div style="display:flex;flex-wrap:wrap;gap:8px">${brand.relatedSearches.map(q=>`<span style="display:inline-block;padding:8px 14px;background:#f5f5f5;border-radius:20px;font-size:13px;color:#555">${escHtml(q)}</span>`).join('')}</div></section>`:'';
    const head=`<title>${escHtml(brand.title)}</title><meta name="description" content="${escHtml(brand.metaDesc)}"><meta name="keywords" content="${escHtml(brand.keywords||'')}"><meta name="robots" content="index, follow"><link rel="canonical" href="${BASE}/brand/${brandSlug}"><meta property="og:type" content="website"><meta property="og:title" content="${escHtml(brand.name)} — купити електросамокат | RideGO"><meta property="og:description" content="${escHtml(brand.metaDesc)}"><meta property="og:url" content="${BASE}/brand/${brandSlug}"><meta property="og:site_name" content="RideGO"><meta property="og:image" content="${BASE}/og-image.png"><meta property="og:locale" content="uk_UA"><script type="application/ld+json">${bcs}</script><script type="application/ld+json">${ils}</script>${faqs?`<script type="application/ld+json">${faqs}</script>`:''}`;
    const body=`<nav class="bc" aria-label="Breadcrumb"><a href="${BASE}">RideGO</a><span>›</span><a href="${BASE}/catalog">Каталог</a><span>›</span><a href="${BASE}/category/${brand.catSlug}">${escHtml(brand.category)}</a><span>›</span><span>${escHtml(brand.name)}</span></nav><h1>${escHtml(brand.icon)} ${escHtml(brand.h1)}</h1><p style="color:#666;margin-bottom:24px;font-size:15px">Знайдено <strong>${listings.length}</strong> оголошень ${escHtml(brand.name)} на маркетплейсі RideGO</p>${brand.introHtml||''}<section><h2 style="font-size:17px;font-weight:700;margin-bottom:16px;color:#111">Оголошення ${escHtml(brand.name)} <span style="color:#888;font-weight:400;font-size:14px">(${listings.length})</span></h2><div class="grid">${lHtml}</div></section>${faqH}${relH}<section style="padding:28px;background:#f0fdf4;border-radius:16px;text-align:center;margin-bottom:32px"><h2 style="font-size:19px;font-weight:700;margin-bottom:8px">Продаєте ${escHtml(brand.name)}?</h2><p style="color:#555;margin-bottom:16px">Розмістіть оголошення безкоштовно на RideGO</p><a href="${BASE}/add" style="display:inline-block;background:#1db954;color:#fff;padding:13px 28px;border-radius:10px;text-decoration:none;font-weight:700">Подати оголошення →</a></section>`;
    res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','s-maxage=1800, stale-while-revalidate=3600');return res.status(200).send(shell(head,body));
  }

  // CATEGORY PAGE
  const catName=catInfo?.name||slug; const catDesc=catInfo?.desc||`Купити ${catName} в Україні на маркетплейсі RideGO.`;
  const listings=await getListingsByCategory(catName);
  const lHtml=listings.length?listings.map(l=>card(l)).join('\n'):'<p style="color:#888;grid-column:1/-1">Оголошень поки немає</p>';
  const otherCats=Object.entries(CATEGORIES).filter(([s])=>s!==slug).map(([s,info])=>`<a href="${BASE}/category/${s}" style="display:inline-flex;align-items:center;gap:5px;padding:8px 14px;background:#f0fdf4;border-radius:8px;text-decoration:none;color:#166534;font-size:13px;font-weight:600;margin:3px">${info.icon} ${escHtml(info.name)}</a>`).join('');
  const ils=JSON.stringify({"@context":"https://schema.org","@type":"ItemList","name":`${catName} — RideGO`,"url":`${BASE}/category/${slug}`,"numberOfItems":listings.length,"itemListElement":listings.map((l,i)=>({"@type":"ListItem","position":i+1,"url":`${BASE}/listing/${l.id}`,"name":l.title}))});
  const bcs=JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"RideGO","item":BASE},{"@type":"ListItem","position":2,"name":"Каталог","item":`${BASE}/catalog`},{"@type":"ListItem","position":3,"name":catName,"item":`${BASE}/category/${slug}`}]});
  const head=`<title>${escHtml(catName)} — купити в Україні, ціни, оголошення | RideGO</title><meta name="description" content="${escHtml(catDesc)}"><meta name="robots" content="index, follow"><link rel="canonical" href="${BASE}/category/${slug}"><meta property="og:type" content="website"><meta property="og:title" content="${escHtml(catName)} — RideGO"><meta property="og:description" content="${escHtml(catDesc)}"><meta property="og:url" content="${BASE}/category/${slug}"><meta property="og:site_name" content="RideGO"><meta property="og:locale" content="uk_UA"><script type="application/ld+json">${bcs}</script><script type="application/ld+json">${ils}</script>`;
  const body=`<nav class="bc" aria-label="Breadcrumb"><a href="${BASE}">RideGO</a><span>›</span><a href="${BASE}/catalog">Каталог</a><span>›</span><span>${escHtml(catName)}</span></nav><h1>${escHtml(catInfo?.icon||'')} ${escHtml(catName)}</h1><p style="color:#666;margin-bottom:24px;font-size:15px">${escHtml(catDesc)}</p><section style="margin-bottom:28px"><h2 style="font-size:17px;font-weight:700;margin-bottom:12px">Оголошення <span style="color:#888;font-weight:400;font-size:14px">(${listings.length})</span></h2><div class="grid">${lHtml}</div></section><section style="margin-bottom:28px"><h2 style="font-size:16px;font-weight:700;margin-bottom:12px">Інші категорії</h2><div>${otherCats}</div></section>${slug==='elektrosamokaty'?`<section style="margin-bottom:28px"><h2 style="font-size:16px;font-weight:700;margin-bottom:12px">Популярні бренди електросамокатів</h2><div><a href="${BASE}/brand/kukirin" style="display:inline-flex;align-items:center;gap:5px;padding:8px 14px;background:#f0fdf4;border-radius:8px;text-decoration:none;color:#166534;font-size:13px;font-weight:600;margin:3px">⚡ KuKirin (Kugoo Kirin)</a></div></section>`:''}`;
  res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','s-maxage=3600, stale-while-revalidate=86400');res.status(200).send(shell(head,body));
};
