const BASE = 'https://www.ridego.com.ua';
const PROJECT = 'ridego-6f981';
const BOTS = /googlebot|bingbot|slurp|duckduckbot|baiduspider|yandexbot|facebookexternalhit|twitterbot|linkedinbot|telegrambot|whatsapp|applebot|mj12bot|ahrefsbot|semrushbot|petalbot|bytespider|google-inspectiontool|google-structured-data-testing|storebot|developers\.google/i;

const CATEGORIES = {
  'elektrosamokaty':   { name: 'Електросамокати', icon: '⚡', desc: 'Купити електросамокат в Україні — великий вибір нових та вживаних електросамокатів від приватних продавців і магазинів за вигідними цінами.' },
  'velosypedy':        { name: 'Велосипеди', icon: '🚲', desc: 'Купити велосипед в Україні — гірські, міські, дорожні велосипеди від приватних продавців за доступними цінами.' },
  'elektrovelosypedy': { name: 'Електровелосипеди', icon: '🚴', desc: 'Купити електровелосипед в Україні — новітні моделі електровелосипедів для міста та бездоріжжя.' },
  'elektroskutery':    { name: 'Електроскутери', icon: '🛵', desc: 'Купити електроскутер в Україні — широкий вибір електроскутерів для міських поїздок за найкращими цінами.' },
  'elektromotocykly':  { name: 'Електромотоцикли', icon: '🏍', desc: 'Купити електромотоцикл в Україні — потужні електромотоцикли для активного відпочинку та щоденних поїздок.' },
};

// ─── BRANDS ───
const BRANDS = {
  'kukirin': {
    name: 'KuKirin', firebaseNames: ['Kukirin','KuKirin','Kugoo'], category: 'Електросамокати', catSlug: 'elektrosamokaty', icon: '⚡',
    title: 'Купити електросамокат KuKirin (Кукірін) в Україні — ціни, моделі | RideGO',
    h1: 'Електросамокати KuKirin — купити в Україні',
    metaDesc: 'Електросамокати KuKirin (Кукірін, Kugoo Kirin) — купити в Україні на маркетплейсі RideGO. Моделі G2, G2 Pro, G2 Max, G3, G4, M4 Pro, S1 Max. Нові та б/в, ціни від продавців по всій Україні.',
    keywords: 'купити KuKirin, KuKirin ціна, електросамокат KuKirin, купити Kukirin, купити Kugoo Kirin, купити Кукірін, купити Кукирін, купити Кукирин, KuKirin Україна, KuKirin Київ, KuKirin б/в',
    introHtml: '<div style="background:#f0fdf4;border-radius:16px;padding:24px 28px;margin-bottom:28px;line-height:1.8;font-size:15px;color:#333"><h2 style="font-size:20px;font-weight:800;margin-bottom:12px;color:#111">KuKirin (Кукірін) — електросамокати для міста та бездоріжжя</h2><p><strong>KuKirin</strong> (також відомий як <strong>Kugoo Kirin</strong>, Кукірін, Кукирін) — один із найпопулярніших брендів електросамокатів в Україні. Бренд пропонує широку лінійку моделей: від компактних міських (<strong>KuKirin S1 Max</strong>, <strong>KuKirin A1</strong>) до потужних позашляховиків (<strong>KuKirin G2 Pro</strong>, <strong>KuKirin G3</strong>, <strong>KuKirin G4</strong>) та моделей із сидінням (<strong>KuKirin M4 Pro</strong>, <strong>KuKirin M5 Pro</strong>).</p><p style="margin-top:12px">На маркетплейсі <strong>RideGO</strong> ви можете <strong>купити електросамокат KuKirin</strong> як новий, так і б/в — від приватних продавців та магазинів по всій Україні.</p><h3 style="font-size:17px;font-weight:700;margin-top:20px;margin-bottom:10px;color:#111">Популярні моделі KuKirin</h3><ul style="margin:0;padding-left:20px;color:#444"><li><strong>KuKirin G2</strong> — 800 Вт, 48V 15Ah, до 60 км запас ходу.</li><li><strong>KuKirin G2 Pro</strong> — покращена версія з посиленою рамою.</li><li><strong>KuKirin G2 Max</strong> — 1000 Вт, 20Ah, до 70 км ходу.</li><li><strong>KuKirin G3 / G3 Pro</strong> — подвійний двигун до 1200 Вт.</li><li><strong>KuKirin G4</strong> — 2000 Вт, до 69 км/год. Флагман.</li><li><strong>KuKirin M4 Pro</strong> — з сидінням, 1500 Вт, NFC.</li><li><strong>KuKirin S1 Max</strong> — легкий 16 кг, складний.</li><li><strong>KuKirin T3</strong> — 800 Вт, золота середина.</li><li><strong>KuKirin C1 Pro</strong> — 14" колеса, до 100 км ходу.</li></ul></div>',
    faqItems: [
      { q: 'Скільки коштує електросамокат KuKirin в Україні?', a: 'Ціни починаються від ~14 000 грн (S1 Max) до ~40 000 грн (G4, G2 Master). Вживані дешевше.' },
      { q: 'Який KuKirin вибрати для міста?', a: 'KuKirin G2 (800 Вт, до 60 км) або S1 Max (16 кг). Для поганих доріг — G2 Pro.' },
      { q: 'Чим KuKirin відрізняється від Kugoo?', a: 'KuKirin — ребрендинг Kugoo Kirin. Той самий виробник, новий бренд.' },
      { q: 'Де купити оригінальний KuKirin?', a: 'На маркетплейсі RideGO — порівняйте ціни від продавців по всій Україні.' },
      { q: 'Який запас ходу у KuKirin?', a: 'S1 Max — 40 км, G2 — 60 км, G2 Max — 70 км, C1 Pro — 100 км.' }
    ],
    relatedSearches: ['купити kukirin g2','kukirin g2 pro ціна','kukirin g4 купити','kukirin m4 pro ціна','електросамокат kukirin ціна','kukirin або ninebot'],
    models: ['g2','g2-pro','g2-max','g3','g3-pro','g4','g4-max','m4-pro','m5-pro','s1-max','t3','c1-pro']
  },
};

// ─── MODELS (SEO сторінки під кожну модель) ───
const MODELS = {
  'kukirin-g2':     { brand:'kukirin', model:'G2', searchTerms:['G2','Kirin G2'], power:'800W', battery:'48V 15Ah', range:'60 км', speed:'45 км/год', weight:'24 кг', title:'KuKirin G2 — купити в Україні ⚡ ціна 2026, характеристики | RideGO', h1:'Електросамокат KuKirin G2 — купити в Україні', metaDesc:'Купити електросамокат KuKirin G2 (800W, 48V 15Ah) в Україні. Ціна, характеристики, відгуки. Запас ходу до 60 км. Нові та б/в на маркетплейсі RideGO.', text:'KuKirin G2 — універсальний міський електросамокат з двигуном 800 Вт та батареєю 48V 15Ah. Запас ходу до 60 км, максимальна швидкість 45 км/год. 10-дюймові пневматичні шини забезпечують комфортну їзду по будь-якому покриттю. Оновлена версія 2025 року отримала збільшені гальмівні диски (160 мм), посилений задній крило та водозахисну платформу.' },
  'kukirin-g2-pro': { brand:'kukirin', model:'G2 Pro', searchTerms:['G2 Pro','G2Pro','Kirin G2 Pro'], power:'600W', battery:'48V 15Ah', range:'55 км', speed:'45 км/год', weight:'23 кг', title:'KuKirin G2 Pro — купити в Україні ⚡ ціна, відгуки | RideGO', h1:'Електросамокат KuKirin G2 Pro — купити в Україні', metaDesc:'Купити KuKirin G2 Pro в Україні. 600W, 48V 15Ah, до 55 км ходу. Покращена амортизація та гальма. Ціни на RideGO.', text:'KuKirin G2 Pro — покращена версія G2 з посиленою рамою, збільшеними гальмівними дисками та покращеною підвіскою. Двигун 600 Вт забезпечує впевнений розгін, а батарея 15Ah — до 55 км ходу.' },
  'kukirin-g2-max': { brand:'kukirin', model:'G2 Max', searchTerms:['G2 Max','G2Max','Kirin G2 Max'], power:'1000W', battery:'48V 20Ah', range:'70 км', speed:'55 км/год', weight:'28 кг', title:'KuKirin G2 Max — купити в Україні ⚡ ціна 2026 | RideGO', h1:'Електросамокат KuKirin G2 Max — купити в Україні', metaDesc:'KuKirin G2 Max (1000W, 20Ah) — купити в Україні. До 70 км ходу, 55 км/год. Ціни від продавців на RideGO.', text:'KuKirin G2 Max — версія з максимальним запасом ходу в лінійці G2. Потужний двигун 1000 Вт, батарея 48V 20Ah забезпечує до 70 км на одному заряді. Ідеальний для далеких поїздок та приміських маршрутів.' },
  'kukirin-g3':     { brand:'kukirin', model:'G3', searchTerms:['G3','Kirin G3'], power:'1200W', battery:'52V 18Ah', range:'60 км', speed:'50 км/год', weight:'27 кг', title:'KuKirin G3 — купити в Україні ⚡ ціна, характеристики | RideGO', h1:'Електросамокат KuKirin G3 — купити в Україні', metaDesc:'KuKirin G3 (1200W, 52V 18Ah) — купити в Україні. Потужний позашляховик з подвійним двигуном. Ціни на RideGO.', text:'KuKirin G3 — потужний позашляховий електросамокат з двигуном 1200 Вт. Батарея 52V 18Ah, запас ходу до 60 км. Великі пневматичні шини та подвійна амортизація для бездоріжжя.' },
  'kukirin-g3-pro': { brand:'kukirin', model:'G3 Pro', searchTerms:['G3 Pro','G3Pro'], power:'1200W×2', battery:'52V 18Ah', range:'70 км', speed:'50 км/год', weight:'32 кг', title:'KuKirin G3 Pro — купити в Україні ⚡ ціна | RideGO', h1:'Електросамокат KuKirin G3 Pro — купити в Україні', metaDesc:'KuKirin G3 Pro — повнопривідний (2×1200W). Купити в Україні, ціни на RideGO.', text:'KuKirin G3 Pro — повнопривідна версія з подвійним двигуном (2×1200 Вт). До 70 км ходу, просунута система амортизації. Створений для бездоріжжя та складних умов.' },
  'kukirin-g4':     { brand:'kukirin', model:'G4', searchTerms:['G4','Kirin G4'], power:'2000W', battery:'60V 20Ah', range:'70 км', speed:'69 км/год', weight:'35 кг', title:'KuKirin G4 — купити в Україні ⚡ ціна 2026, наявність | RideGO', h1:'Електросамокат KuKirin G4 — купити в Україні', metaDesc:'Купити KuKirin G4 (2000W, 60V 20Ah) в Україні. Швидкість до 69 км/год, запас ходу 70 км. Ціни, наявність, доставка на RideGO.', text:'KuKirin G4 — флагманський електросамокат бренду. Потужний задній двигун 2000 Вт, батарея 60V 20Ah, максимальна швидкість до 69 км/год. Гідравлічна підвіска, гідравлічні гальма, 10-дюймові позашляхові шини. Це серйозний апарат для досвідчених райдерів.' },
  'kukirin-g4-max': { brand:'kukirin', model:'G4 Max', searchTerms:['G4 Max','G4Max'], power:'2000W', battery:'60V 28Ah', range:'90 км', speed:'69 км/год', weight:'38 кг', title:'KuKirin G4 Max — купити в Україні ⚡ ціна | RideGO', h1:'Електросамокат KuKirin G4 Max — купити в Україні', metaDesc:'KuKirin G4 Max (2000W, 28Ah) — до 90 км ходу. Купити в Україні на RideGO.', text:'KuKirin G4 Max — версія G4 зі збільшеною батареєю 28Ah. До 90 км ходу на одному заряді, гідравлічна підвіска та гальма.' },
  'kukirin-m4-pro': { brand:'kukirin', model:'M4 Pro', searchTerms:['M4 Pro','M4Pro','Kirin M4 Pro','M4 PRO'], power:'1500W', battery:'48V 21Ah', range:'65 км', speed:'50 км/год', weight:'30 кг', title:'KuKirin M4 Pro — купити в Україні ⚡ з сидінням | RideGO', h1:'Електросамокат KuKirin M4 Pro — купити в Україні', metaDesc:'KuKirin M4 Pro з сидінням (1500W, 21Ah) — купити в Україні. NFC-ключ, до 65 км ходу. Ціни на RideGO.', text:'KuKirin M4 Pro — електросамокат з сидінням для комфортних тривалих поїздок. Двигун 1500 Вт, батарея 48V 21Ah, NFC-ключ для захисту від крадіжки. Знімне сидіння, LED-фари.' },
  'kukirin-s1-max': { brand:'kukirin', model:'S1 Max', searchTerms:['S1 Max','S1Max','Kirin S1 Max'], power:'350W', battery:'36V 10.4Ah', range:'40 км', speed:'25 км/год', weight:'16 кг', title:'KuKirin S1 Max — купити в Україні ⚡ легкий, складний | RideGO', h1:'Електросамокат KuKirin S1 Max — купити в Україні', metaDesc:'KuKirin S1 Max (350W, 16 кг) — легкий складний електросамокат. Купити в Україні, ціни на RideGO.', text:'KuKirin S1 Max — компактний та легкий електросамокат вагою лише 16 кг. Двигун 350 Вт, батарея 36V 10.4Ah, до 40 км ходу. Ідеальний для щоденних міських поїздок та останньої милі.' },
  'kukirin-t3':     { brand:'kukirin', model:'T3', searchTerms:['T3','Kirin T3'], power:'800W', battery:'48V 15.6Ah', range:'55 км', speed:'45 км/год', weight:'22 кг', title:'KuKirin T3 — купити в Україні ⚡ ціна, огляд | RideGO', h1:'Електросамокат KuKirin T3 — купити в Україні', metaDesc:'KuKirin T3 (800W, 15.6Ah) — купити в Україні. Золота середина ціна/якість. Ціни на RideGO.', text:'KuKirin T3 — збалансований електросамокат з двигуном 800 Вт та батареєю 15.6Ah. 10-дюймові пневматичні колеса, подвійна амортизація. Відмінне співвідношення ціна/якість.' },
  'kukirin-c1-pro': { brand:'kukirin', model:'C1 Pro', searchTerms:['C1 Pro','C1Pro','Kirin C1 Pro'], power:'500W', battery:'48V 26Ah', range:'100 км', speed:'40 км/год', weight:'28 кг', title:'KuKirin C1 Pro — купити в Україні ⚡ до 100 км ходу | RideGO', h1:'Електросамокат KuKirin C1 Pro — купити в Україні', metaDesc:'KuKirin C1 Pro (500W, 26Ah, 14" колеса) — до 100 км ходу. Купити в Україні на RideGO.', text:'KuKirin C1 Pro — електросамокат з великими 14-дюймовими колесами та рекордною батареєю 26Ah. До 100 км ходу на одному заряді. Ідеальний для далеких комфортних поїздок.' },
  'kukirin-m5-pro': { brand:'kukirin', model:'M5 Pro', searchTerms:['M5 Pro','M5Pro','Kirin M5 Pro','M5 PRO'], power:'2000W', battery:'48V 26Ah', range:'70 км', speed:'55 км/год', weight:'35 кг', title:'KuKirin M5 Pro — купити в Україні ⚡ потужний | RideGO', h1:'Електросамокат KuKirin M5 Pro — купити в Україні', metaDesc:'KuKirin M5 Pro (2000W, 26Ah) — потужний електросамокат з сидінням. Купити в Україні на RideGO.', text:'KuKirin M5 Pro — потужний електросамокат з сидінням. Двигун 2000 Вт, батарея 48V 26Ah. До 70 км ходу, швидкість до 55 км/год.' },
};

function escHtml(str) { return String(str||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }

async function getListingsByCategory(catName) {
  try {
    const url = `https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents:runQuery`;
    const body = { structuredQuery: { from:[{collectionId:'listings'}], where:{compositeFilter:{op:'AND',filters:[{fieldFilter:{field:{fieldPath:'cat'},op:'EQUAL',value:{stringValue:catName}}},{fieldFilter:{field:{fieldPath:'status'},op:'EQUAL',value:{stringValue:'active'}}}]}}, orderBy:[{field:{fieldPath:'createdAt'},direction:'DESCENDING'}], limit:20 } };
    const res = await fetch(url, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) });
    if (!res.ok) return [];
    const data = await res.json();
    return data.filter(d=>d.document).map(d=>{ const f=d.document.fields||{}; const id=d.document.name.split('/').pop(); return { id, title:f.title?.stringValue||'', price:f.price?.integerValue||f.price?.doubleValue||'', city:f.city?.stringValue||'', condition:f.condition?.stringValue||'', img:f.img?.stringValue||'' }; });
  } catch(e) { return []; }
}

async function getListingsByBrand(brandNames, limit) {
  const all=[]; const seen=new Set();
  for (const bn of brandNames) {
    try {
      const url = `https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents:runQuery`;
      const body = { structuredQuery: { from:[{collectionId:'listings'}], where:{compositeFilter:{op:'AND',filters:[{fieldFilter:{field:{fieldPath:'status'},op:'EQUAL',value:{stringValue:'active'}}},{fieldFilter:{field:{fieldPath:'brand'},op:'EQUAL',value:{stringValue:bn}}}]}}, limit:limit||30 } };
      const res = await fetch(url, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) });
      if (res.ok) { const data=await res.json(); data.filter(d=>d.document).forEach(d=>{ const id=d.document.name.split('/').pop(); if(!seen.has(id)){seen.add(id); const f=d.document.fields||{}; all.push({id,title:f.title?.stringValue||'',price:f.price?.integerValue||f.price?.doubleValue||'',city:f.city?.stringValue||'',condition:f.condition?.stringValue||'',img:f.img?.stringValue||''});} }); }
    } catch(e) {}
  }
  return all.slice(0,limit||30);
}

async function getListingsByModel(brandNames, searchTerms, limit) {
  const all = await getListingsByBrand(brandNames, 100);
  const terms = searchTerms.map(t => t.toLowerCase());
  const filtered = all.filter(l => { const t = l.title.toLowerCase(); return terms.some(term => t.includes(term.toLowerCase())); });
  return filtered.slice(0, limit || 20);
}

function getParam(req,key) { if(req.query&&req.query[key]) return req.query[key]; try{ const qs=(req.url||'').split('?')[1]||''; for(const p of qs.split('&')){const[k,v]=p.split('='); if(decodeURIComponent(k||'')===key) return decodeURIComponent(v||'');} }catch(e){} return ''; }

function card(l) { const price=l.price?Number(l.price).toLocaleString('uk')+' грн':''; return `<article style="border:1px solid #eee;border-radius:12px;overflow:hidden">${l.img?`<a href="${BASE}/listing/${l.id}"><img src="${escHtml(l.img)}" alt="${escHtml(l.title+(l.city?' купити в '+l.city:''))}" width="400" height="240" loading="lazy" style="width:100%;height:160px;object-fit:cover;display:block"></a>`:''}<div style="padding:12px"><a href="${BASE}/listing/${l.id}" style="font-weight:700;color:#111;text-decoration:none;font-size:15px;display:block;margin-bottom:4px">${escHtml(l.title)}</a>${price?`<div style="color:#1db954;font-weight:800;font-size:16px;margin-bottom:4px">${price}</div>`:''}<div style="color:#888;font-size:13px">${escHtml(l.city)}${l.condition?' · '+escHtml(l.condition):''}</div></div></article>`; }

function shell(head,body) { return `<!DOCTYPE html><html lang="uk"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">${head}<link rel="icon" type="image/svg+xml" href="/favicon.svg"><style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',Arial,sans-serif;max-width:980px;margin:0 auto;padding:20px;color:#222;background:#fff}header{padding:16px 0;border-bottom:2px solid #1db954;margin-bottom:20px}header a{font-size:26px;font-weight:800;color:#111;text-decoration:none}header a span{color:#1db954}.bc{font-size:13px;color:#888;margin-bottom:20px}.bc a{color:#1db954;text-decoration:none}.bc span{margin:0 5px;color:#ccc}h1{font-size:clamp(22px,4vw,34px);font-weight:800;margin-bottom:8px;color:#111}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:16px;margin-bottom:32px}footer{padding:20px 0;border-top:1px solid #eee;font-size:13px;color:#999;text-align:center;margin-top:32px}footer a{color:#1db954;text-decoration:none;margin:0 8px}details summary{list-style:none}details summary::-webkit-details-marker{display:none}details summary::before{content:'▸ ';color:#1db954}details[open] summary::before{content:'▾ '}.specs{border-collapse:collapse;width:100%;margin-bottom:20px;font-size:15px}.specs td{padding:10px 12px;border-bottom:1px solid #f0f0f0}.specs td:first-child{color:#888;width:140px}.specs td:last-child{font-weight:600}</style></head><body><header><a href="${BASE}">Ride<span>GO</span></a></header>${body}<footer><span>© 2024–2026 RideGO</span><a href="${BASE}">Головна</a><a href="${BASE}/catalog">Каталог</a><a href="${BASE}/category/elektrosamokaty">Електросамокати</a><a href="${BASE}/news">Новини</a><a href="${BASE}/faq">FAQ</a></footer></body></html>`; }

module.exports = async (req, res) => {
  const ua=req.headers['user-agent']||''; const isBot=BOTS.test(ua);
  const slug=getParam(req,'slug').replace(/[^a-zA-Z0-9_-]/g,'');
  const brandSlug=getParam(req,'brand').replace(/[^a-zA-Z0-9_-]/g,'').toLowerCase();
  const modelSlug=getParam(req,'model').replace(/[^a-zA-Z0-9_-]/g,'').toLowerCase();

  const isBrand=!!brandSlug; const isModel=!!modelSlug;
  const brand=isBrand?BRANDS[brandSlug]:null;
  const model=isModel?MODELS[modelSlug]:null;
  const catInfo=(!isBrand&&!isModel)?CATEGORIES[slug]:null;

  // Unknown → redirect
  if(isBrand&&!brand){res.setHeader('Location',`${BASE}/catalog`);return res.status(302).end();}
  if(isModel&&!model){res.setHeader('Location',`${BASE}/catalog`);return res.status(302).end();}

  // Non-bot → SPA
  if(!isBot){const fs=require('fs');const path=require('path');try{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, must-revalidate');return res.status(200).send(html);}catch(e){return res.status(302).end();}}

  // ════════════════════════════════════
  // MODEL PAGE SSR  /kukirin-g4
  // ════════════════════════════════════
  if(isModel&&model){
    const br=BRANDS[model.brand]||{};
    const listings=await getListingsByModel(br.firebaseNames||[model.brand], model.searchTerms, 20);
    const lHtml=listings.length?listings.map(l=>card(l)).join('\n'):`<p style="color:#888;grid-column:1/-1">Оголошень поки немає — <a href="${BASE}/add" style="color:#1db954">додайте першим!</a></p>`;

    const specsHtml=`<table class="specs">${model.power?`<tr><td>Двигун</td><td>${escHtml(model.power)}</td></tr>`:''}${model.battery?`<tr><td>Акумулятор</td><td>${escHtml(model.battery)}</td></tr>`:''}${model.range?`<tr><td>Запас ходу</td><td>${escHtml(model.range)}</td></tr>`:''}${model.speed?`<tr><td>Макс. швидкість</td><td>${escHtml(model.speed)}</td></tr>`:''}${model.weight?`<tr><td>Вага</td><td>${escHtml(model.weight)}</td></tr>`:''}</table>`;

    // Other models from same brand
    const otherModels=Object.entries(MODELS).filter(([s,m])=>m.brand===model.brand&&s!==modelSlug).slice(0,6).map(([s,m])=>`<a href="${BASE}/${s}" style="display:inline-flex;align-items:center;gap:5px;padding:8px 14px;background:#f0fdf4;border-radius:8px;text-decoration:none;color:#166534;font-size:13px;font-weight:600;margin:3px">⚡ ${escHtml(br.name||'')} ${escHtml(m.model)}</a>`).join('');

    const bcs=JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"RideGO","item":BASE},{"@type":"ListItem","position":2,"name":"Електросамокати","item":`${BASE}/category/elektrosamokaty`},{"@type":"ListItem","position":3,"name":br.name||'','item':`${BASE}/brand/${model.brand}`},{"@type":"ListItem","position":4,"name":`${br.name||''} ${model.model}`,"item":`${BASE}/${modelSlug}`}]});
    const prodSchema=JSON.stringify({"@context":"https://schema.org","@type":"Product","name":`${br.name||''} ${model.model}`,"description":model.metaDesc,"brand":{"@type":"Brand","name":br.name||''},"offers":{"@type":"AggregateOffer","priceCurrency":"UAH","offerCount":listings.length,"availability":"https://schema.org/InStock","url":`${BASE}/${modelSlug}`}});
    const faqSchema=JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":`Скільки коштує ${br.name} ${model.model}?`,"acceptedAnswer":{"@type":"Answer","text":`Ціни на ${br.name} ${model.model} в Україні можна порівняти на маркетплейсі RideGO. Дивіться актуальні оголошення від продавців.`}},{"@type":"Question","name":`Де купити ${br.name} ${model.model} в Україні?`,"acceptedAnswer":{"@type":"Answer","text":`На маркетплейсі RideGO зібрані оголошення ${br.name} ${model.model} від продавців по всій Україні — Київ, Харків, Одеса, Дніпро, Львів та інші міста.`}},{"@type":"Question","name":`Які характеристики ${br.name} ${model.model}?`,"acceptedAnswer":{"@type":"Answer","text":`${br.name} ${model.model}: двигун ${model.power||'—'}, батарея ${model.battery||'—'}, запас ходу ${model.range||'—'}, макс. швидкість ${model.speed||'—'}.`}}]});

    const head=`<title>${escHtml(model.title)}</title><meta name="description" content="${escHtml(model.metaDesc)}"><meta name="keywords" content="${escHtml(br.name)} ${escHtml(model.model)} купити, ${escHtml(br.name)} ${escHtml(model.model)} ціна, ${escHtml(br.name)} ${escHtml(model.model)} Україна, електросамокат ${escHtml(br.name)} ${escHtml(model.model)}, ${escHtml(br.name)} ${escHtml(model.model)} характеристики, ${escHtml(br.name)} ${escHtml(model.model)} відгуки"><meta name="robots" content="index, follow"><link rel="canonical" href="${BASE}/${modelSlug}"><meta property="og:type" content="product"><meta property="og:title" content="${escHtml(br.name)} ${escHtml(model.model)} — купити в Україні | RideGO"><meta property="og:description" content="${escHtml(model.metaDesc)}"><meta property="og:url" content="${BASE}/${modelSlug}"><meta property="og:site_name" content="RideGO"><meta property="og:image" content="${BASE}/og-image.png"><meta property="og:locale" content="uk_UA"><script type="application/ld+json">${bcs}</script><script type="application/ld+json">${prodSchema}</script><script type="application/ld+json">${faqSchema}</script>`;

    const body=`<nav class="bc" aria-label="Breadcrumb"><a href="${BASE}">RideGO</a><span>›</span><a href="${BASE}/category/elektrosamokaty">Електросамокати</a><span>›</span><a href="${BASE}/brand/${model.brand}">${escHtml(br.name||'')}</a><span>›</span><span>${escHtml(br.name||'')} ${escHtml(model.model)}</span></nav>
<h1>⚡ ${escHtml(model.h1)}</h1>
<p style="color:#666;margin-bottom:20px;font-size:15px">${escHtml(model.metaDesc)}</p>
<section style="margin-bottom:28px"><h2 style="font-size:18px;font-weight:700;margin-bottom:12px;color:#111">Характеристики ${escHtml(br.name)} ${escHtml(model.model)}</h2>${specsHtml}</section>
<section style="margin-bottom:28px;background:#f9f9f9;border-radius:12px;padding:20px;line-height:1.8;font-size:15px;color:#444"><h2 style="font-size:18px;font-weight:700;margin-bottom:10px;color:#111">Про ${escHtml(br.name)} ${escHtml(model.model)}</h2><p>${model.text}</p></section>
<section style="margin-bottom:28px"><h2 style="font-size:17px;font-weight:700;margin-bottom:16px;color:#111">Оголошення ${escHtml(br.name)} ${escHtml(model.model)} <span style="color:#888;font-weight:400;font-size:14px">(${listings.length})</span></h2><div class="grid">${lHtml}</div></section>
<section style="margin-bottom:28px"><h2 style="font-size:17px;font-weight:700;margin-bottom:12px;color:#111">Часті питання</h2><details style="margin-bottom:8px;border:1px solid #eee;border-radius:10px"><summary style="padding:12px 16px;font-weight:600;cursor:pointer;background:#fafafa">Скільки коштує ${escHtml(br.name)} ${escHtml(model.model)}?</summary><div style="padding:12px 16px;font-size:14px;color:#555;line-height:1.7">Актуальні ціни на ${escHtml(br.name)} ${escHtml(model.model)} дивіться в оголошеннях вище. Ціни залежать від стану, комплектації та міста продавця.</div></details><details style="margin-bottom:8px;border:1px solid #eee;border-radius:10px"><summary style="padding:12px 16px;font-weight:600;cursor:pointer;background:#fafafa">Де купити ${escHtml(br.name)} ${escHtml(model.model)} в Україні?</summary><div style="padding:12px 16px;font-size:14px;color:#555;line-height:1.7">На маркетплейсі RideGO зібрані оголошення від продавців по всій Україні — Київ, Харків, Одеса, Дніпро, Львів та інші міста.</div></details><details style="margin-bottom:8px;border:1px solid #eee;border-radius:10px"><summary style="padding:12px 16px;font-weight:600;cursor:pointer;background:#fafafa">Які характеристики ${escHtml(br.name)} ${escHtml(model.model)}?</summary><div style="padding:12px 16px;font-size:14px;color:#555;line-height:1.7">Двигун: ${escHtml(model.power||'—')}, батарея: ${escHtml(model.battery||'—')}, запас ходу: ${escHtml(model.range||'—')}, макс. швидкість: ${escHtml(model.speed||'—')}, вага: ${escHtml(model.weight||'—')}.</div></details></section>
${otherModels?`<section style="margin-bottom:28px"><h2 style="font-size:16px;font-weight:700;margin-bottom:12px">Інші моделі ${escHtml(br.name)}</h2><div>${otherModels}</div><div style="margin-top:12px"><a href="${BASE}/brand/${model.brand}" style="color:#1db954;font-weight:600;text-decoration:none">Всі моделі ${escHtml(br.name)} →</a></div></section>`:''}
<section style="padding:28px;background:#f0fdf4;border-radius:16px;text-align:center;margin-bottom:32px"><h2 style="font-size:19px;font-weight:700;margin-bottom:8px">Продаєте ${escHtml(br.name)} ${escHtml(model.model)}?</h2><p style="color:#555;margin-bottom:16px">Розмістіть оголошення безкоштовно на RideGO</p><a href="${BASE}/add" style="display:inline-block;background:#1db954;color:#fff;padding:13px 28px;border-radius:10px;text-decoration:none;font-weight:700">Подати оголошення →</a></section>`;

    res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','s-maxage=1800, stale-while-revalidate=3600');return res.status(200).send(shell(head,body));
  }

  // ════════════════════════════════════
  // BRAND PAGE SSR  /brand/kukirin
  // ════════════════════════════════════
  if(isBrand&&brand){
    const listings=await getListingsByBrand(brand.firebaseNames,30);
    const lHtml=listings.length?listings.map(l=>card(l)).join('\n'):`<p style="color:#888;grid-column:1/-1">Оголошень поки немає — <a href="${BASE}/add" style="color:#1db954">додайте першим!</a></p>`;
    const modelsHtml=brand.models?`<section style="margin-bottom:28px"><h2 style="font-size:17px;font-weight:700;margin-bottom:12px;color:#111">Моделі ${escHtml(brand.name)}</h2><div style="display:flex;flex-wrap:wrap;gap:8px">${brand.models.map(m=>{const s=brand.name.toLowerCase().replace(/\s+/g,'')+'-'+m; const md=MODELS[s]; return md?`<a href="${BASE}/${s}" style="display:inline-flex;align-items:center;gap:5px;padding:10px 16px;background:#f0fdf4;border-radius:10px;text-decoration:none;color:#111;font-weight:600;font-size:14px;border:1px solid #d1fae5">⚡ ${escHtml(brand.name)} ${escHtml(md.model)}</a>`:''}).filter(Boolean).join('')}</div></section>`:'';
    const ils=JSON.stringify({"@context":"https://schema.org","@type":"ItemList","name":`${brand.name} — купити в Україні | RideGO`,"url":`${BASE}/brand/${brandSlug}`,"numberOfItems":listings.length,"itemListElement":listings.slice(0,20).map((l,i)=>({"@type":"ListItem","position":i+1,"url":`${BASE}/listing/${l.id}`,"name":l.title}))});
    const bcs=JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"RideGO","item":BASE},{"@type":"ListItem","position":2,"name":"Каталог","item":`${BASE}/catalog`},{"@type":"ListItem","position":3,"name":brand.category,"item":`${BASE}/category/${brand.catSlug}`},{"@type":"ListItem","position":4,"name":brand.name,"item":`${BASE}/brand/${brandSlug}`}]});
    const faqs=brand.faqItems?JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":brand.faqItems.map(f=>({"@type":"Question","name":f.q,"acceptedAnswer":{"@type":"Answer","text":f.a}}))}):''
    const faqH=brand.faqItems?`<section style="margin-bottom:32px"><h2 style="font-size:19px;font-weight:800;margin-bottom:16px;color:#111">Часті питання про ${escHtml(brand.name)}</h2>${brand.faqItems.map(f=>`<details style="margin-bottom:10px;border:1px solid #eee;border-radius:10px;overflow:hidden"><summary style="padding:14px 18px;font-weight:700;font-size:15px;cursor:pointer;background:#fafafa;color:#111">${escHtml(f.q)}</summary><div style="padding:14px 18px;font-size:14px;color:#555;line-height:1.7">${escHtml(f.a)}</div></details>`).join('')}</section>`:'';
    const relH=brand.relatedSearches?`<section style="margin-bottom:32px"><h2 style="font-size:16px;font-weight:700;margin-bottom:12px;color:#111">Популярні запити</h2><div style="display:flex;flex-wrap:wrap;gap:8px">${brand.relatedSearches.map(q=>`<span style="display:inline-block;padding:8px 14px;background:#f5f5f5;border-radius:20px;font-size:13px;color:#555">${escHtml(q)}</span>`).join('')}</div></section>`:'';
    const head=`<title>${escHtml(brand.title)}</title><meta name="description" content="${escHtml(brand.metaDesc)}"><meta name="keywords" content="${escHtml(brand.keywords||'')}"><meta name="robots" content="index, follow"><link rel="canonical" href="${BASE}/brand/${brandSlug}"><meta property="og:type" content="website"><meta property="og:title" content="${escHtml(brand.name)} — купити електросамокат | RideGO"><meta property="og:description" content="${escHtml(brand.metaDesc)}"><meta property="og:url" content="${BASE}/brand/${brandSlug}"><meta property="og:site_name" content="RideGO"><meta property="og:image" content="${BASE}/og-image.png"><meta property="og:locale" content="uk_UA"><script type="application/ld+json">${bcs}</script><script type="application/ld+json">${ils}</script>${faqs?`<script type="application/ld+json">${faqs}</script>`:''}`;
    const body=`<nav class="bc" aria-label="Breadcrumb"><a href="${BASE}">RideGO</a><span>›</span><a href="${BASE}/catalog">Каталог</a><span>›</span><a href="${BASE}/category/${brand.catSlug}">${escHtml(brand.category)}</a><span>›</span><span>${escHtml(brand.name)}</span></nav><h1>${escHtml(brand.icon)} ${escHtml(brand.h1)}</h1><p style="color:#666;margin-bottom:24px;font-size:15px">Знайдено <strong>${listings.length}</strong> оголошень ${escHtml(brand.name)} на маркетплейсі RideGO</p>${brand.introHtml||''}${modelsHtml}<section><h2 style="font-size:17px;font-weight:700;margin-bottom:16px;color:#111">Оголошення ${escHtml(brand.name)} <span style="color:#888;font-weight:400;font-size:14px">(${listings.length})</span></h2><div class="grid">${lHtml}</div></section>${faqH}${relH}<section style="padding:28px;background:#f0fdf4;border-radius:16px;text-align:center;margin-bottom:32px"><h2 style="font-size:19px;font-weight:700;margin-bottom:8px">Продаєте ${escHtml(brand.name)}?</h2><p style="color:#555;margin-bottom:16px">Розмістіть оголошення безкоштовно на RideGO</p><a href="${BASE}/add" style="display:inline-block;background:#1db954;color:#fff;padding:13px 28px;border-radius:10px;text-decoration:none;font-weight:700">Подати оголошення →</a></section>`;
    res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','s-maxage=1800, stale-while-revalidate=3600');return res.status(200).send(shell(head,body));
  }

  // ════════════════════════════════════
  // CATEGORY PAGE SSR  /category/elektrosamokaty
  // ════════════════════════════════════
  const catName=catInfo?.name||slug; const catDesc=catInfo?.desc||`Купити ${catName} в Україні на маркетплейсі RideGO.`;
  const listings=await getListingsByCategory(catName);
  const lHtml=listings.length?listings.map(l=>card(l)).join('\n'):'<p style="color:#888;grid-column:1/-1">Оголошень поки немає</p>';
  const otherCats=Object.entries(CATEGORIES).filter(([s])=>s!==slug).map(([s,info])=>`<a href="${BASE}/category/${s}" style="display:inline-flex;align-items:center;gap:5px;padding:8px 14px;background:#f0fdf4;border-radius:8px;text-decoration:none;color:#166534;font-size:13px;font-weight:600;margin:3px">${info.icon} ${escHtml(info.name)}</a>`).join('');
  const ils=JSON.stringify({"@context":"https://schema.org","@type":"ItemList","name":`${catName} — RideGO`,"url":`${BASE}/category/${slug}`,"numberOfItems":listings.length,"itemListElement":listings.map((l,i)=>({"@type":"ListItem","position":i+1,"url":`${BASE}/listing/${l.id}`,"name":l.title}))});
  const bcs=JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"RideGO","item":BASE},{"@type":"ListItem","position":2,"name":"Каталог","item":`${BASE}/catalog`},{"@type":"ListItem","position":3,"name":catName,"item":`${BASE}/category/${slug}`}]});
  const head=`<title>${escHtml(catName)} — купити в Україні, ціни, оголошення | RideGO</title><meta name="description" content="${escHtml(catDesc)}"><meta name="robots" content="index, follow"><link rel="canonical" href="${BASE}/category/${slug}"><meta property="og:type" content="website"><meta property="og:title" content="${escHtml(catName)} — RideGO"><meta property="og:description" content="${escHtml(catDesc)}"><meta property="og:url" content="${BASE}/category/${slug}"><meta property="og:site_name" content="RideGO"><meta property="og:locale" content="uk_UA"><script type="application/ld+json">${bcs}</script><script type="application/ld+json">${ils}</script>`;
  const body=`<nav class="bc" aria-label="Breadcrumb"><a href="${BASE}">RideGO</a><span>›</span><a href="${BASE}/catalog">Каталог</a><span>›</span><span>${escHtml(catName)}</span></nav><h1>${escHtml(catInfo?.icon||'')} ${escHtml(catName)}</h1><p style="color:#666;margin-bottom:24px;font-size:15px">${escHtml(catDesc)}</p><section style="margin-bottom:28px"><h2 style="font-size:17px;font-weight:700;margin-bottom:12px">Оголошення <span style="color:#888;font-weight:400;font-size:14px">(${listings.length})</span></h2><div class="grid">${lHtml}</div></section><section style="margin-bottom:28px"><h2 style="font-size:16px;font-weight:700;margin-bottom:12px">Інші категорії</h2><div>${otherCats}</div></section>${slug==='elektrosamokaty'?`<section style="margin-bottom:28px"><h2 style="font-size:16px;font-weight:700;margin-bottom:12px">Популярні бренди електросамокатів</h2><div><a href="${BASE}/brand/kukirin" style="display:inline-flex;align-items:center;gap:5px;padding:8px 14px;background:#f0fdf4;border-radius:8px;text-decoration:none;color:#166534;font-size:13px;font-weight:600;margin:3px">⚡ KuKirin (Kugoo Kirin)</a></div></section>`:''}`;
  res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','s-maxage=3600, stale-while-revalidate=86400');res.status(200).send(shell(head,body));
};
